# Generated by Django 4.1.2 on 2022-11-08 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal_GrupoSecundario1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('vertebracion', models.CharField(max_length=15)),
                ('extremidades', models.IntegerField()),
                ('tipo', models.CharField(max_length=15)),
                ('mandibula', models.BooleanField()),
                ('alimentacion', models.CharField(max_length=15)),
                ('conducta', models.CharField(max_length=150)),
                ('Subfilo_Vertebrado', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Animal_GrupoSecundario2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('vertebracion', models.CharField(max_length=15)),
                ('extremidades', models.IntegerField()),
                ('tipo', models.CharField(max_length=15)),
                ('mandibula', models.BooleanField()),
                ('alimentacion', models.CharField(max_length=15)),
                ('conducta', models.CharField(max_length=150)),
                ('Subfilo_Invertebrado', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_dEntrada', models.DateField()),
                ('turno', models.TimeField()),
            ],
        ),
    ]
