# Generated by Django 4.1.2 on 2022-11-08 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appzoologico', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal_gruposecundario1',
            name='Subfilo_Vertebrado',
        ),
        migrations.RemoveField(
            model_name='animal_gruposecundario2',
            name='Subfilo_Invertebrado',
        ),
    ]
