# Generated by Django 4.1.2 on 2022-11-12 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appzoologico', '0002_remove_animal_gruposecundario1_subfilo_vertebrado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal_gruposecundario1',
            name='mandibula',
        ),
        migrations.RemoveField(
            model_name='animal_gruposecundario1',
            name='vertebracion',
        ),
        migrations.RemoveField(
            model_name='animal_gruposecundario2',
            name='mandibula',
        ),
        migrations.RemoveField(
            model_name='animal_gruposecundario2',
            name='vertebracion',
        ),
    ]
