# Generated by Django 4.1.2 on 2022-11-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appzoologico', '0005_remove_animal_gruposecundario1_tipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='turno',
        ),
        migrations.AddField(
            model_name='empleado',
            name='descripcion',
            field=models.TextField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='empleado',
            name='rol',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
