# Generated by Django 4.1.2 on 2022-11-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appzoologico', '0006_remove_empleado_turno_empleado_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='descripcion',
            field=models.TextField(default='', max_length=80),
        ),
    ]
