# Generated by Django 4.1.2 on 2022-11-23 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appzoologico', '0008_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal_gruposecundario1',
            name='imagenAnimal',
            field=models.ImageField(blank=True, null=True, upload_to='animalesImg'),
        ),
        migrations.AddField(
            model_name='animal_gruposecundario2',
            name='imagenAnimal',
            field=models.ImageField(blank=True, null=True, upload_to='animalesImg'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='imagenEmpleado',
            field=models.ImageField(blank=True, null=True, upload_to='empleadosImg'),
        ),
    ]
