# Generated by Django 4.1.2 on 2022-11-24 02:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appzoologico', '0010_alter_animal_gruposecundario1_conducta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal_gruposecundario1',
            name='extremidades',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='animal_gruposecundario2',
            name='extremidades',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
