# Generated by Django 4.1.2 on 2022-11-24 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appzoologico', '0012_posteo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteo',
            name='posteo',
            field=models.TextField(max_length=1000),
        ),
    ]
