# Generated by Django 4.1.2 on 2022-11-24 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appzoologico', '0013_alter_posteo_posteo'),
    ]

    operations = [
        migrations.AddField(
            model_name='posteo',
            name='animal',
            field=models.CharField(default='', max_length=80),
        ),
    ]
