# Generated by Django 4.1.2 on 2022-11-25 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appzoologico', '0014_posteo_animal'),
    ]

    operations = [
        migrations.AddField(
            model_name='posteo',
            name='avatar_url',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='posteo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='posts'),
        ),
        migrations.AlterField(
            model_name='posteo',
            name='posteo',
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='posteo',
            name='subtitulo',
            field=models.TextField(max_length=300),
        ),
    ]
