# Generated by Django 4.1.2 on 2022-11-25 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appzoologico', '0015_posteo_avatar_url_posteo_imagen_alter_posteo_posteo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteo',
            name='avatar_url',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='posteo',
            name='posteo',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='posteo',
            name='subtitulo',
            field=models.TextField(max_length=400),
        ),
    ]
